name: sm8650-build (dispatch)
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_dispatch:  # This allows this workflow to be called from another workflow
    inputs:
      CPU:
        description: 'CPU分支'
        required: true
        type: choice
        options:
          - 'sm8650'
          - 'sm8550'
          - 'sm8450'
          - 'sm8475'
          - 'sm7675'
          - 'sm7550'
        default: 'sm8650'
        
      CPUD:
        description: '处理器代号'
        required: true
        type: choice
        options:
          - 'pineapple'
          - 'kalama'
          - 'waipio'
          - 'crow'
        default: 'pineapple'
        
      ANDROID_VERSION:
        description: '内核安卓版本'
        required: true
        type: choice
        options:
          - 'android14'
          - 'android13'
          - 'android12'
        default: 'android14'
        
      KERNEL_VERSION:
        description: '内核版本'
        required: true
        type: choice
        options:
          - '6.1'
          - '5.15'
          - '5.10'
        default: '6.1'
        
      KPM:
       description: '是否启用KPM'
       required: true
       type: choice
       options:
           - 'On'
           - 'Off'
       default: 'Off'
       
      lz4kd:
       description: '是否启用lz4kd(关闭则6.1系启用lz4 + zstd)'
       required: true
       type: choice
       options:
          - 'On'
          - 'Off'
       default: 'Off'
       
      bbr:
       description: '是否启用bbr算法(优化上行数据, 对手机日用无太大意义甚至可能负优化)'
       required: true
       type: choice
       options:
          - 'On'
          - 'Off'
       default: 'Off'

      proxy:
       description: '是否添加代理性能优化'
       required: true
       type: choice
       options:
          - 'On'
          - 'Off'
       default: 'On'
  
jobs:
  # 此处是一组任务，代表了sm8650的固定参数
  # 你还需要添加其他的组
  sm8650:
    uses: ./.github/workflows/kernel-sm8650.yml
    secrets: inherit
    with:
      CPU: "sm8650"
      CPUD: "pineapple"
      ANDROID_VERSION: "android14"
      KERNEL_VERSION: "6.1"
      KPM: "Off"
      lz4kd: "Off"
      bbr: "Off"
      proxy: "On"

  # sm8650:  --这里是任务名，用代号区分下就行
  #   uses: ./.github/workflows/kernel-sm8650.yml --由于一个文件代表一个处理器代号，这里也要使用你新建的其他文件
  #   secrets: inherit
  #   with:
    # 下面的参数跟sm xxxx 对应就行了，8650就填8650的
  #     CPU: "sm8650" 
  #     CPUD: "pineapple"
  #     ANDROID_VERSION: "android14"
  #     KERNEL_VERSION: "6.1"
  #     KPM: "Off"
  #     lz4kd: "Off"
  #     bbr: "Off"
  #     proxy: "On"