name: sm8650-build
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call: 
jobs:
  build-kernel-sm8650: # 这里也可以改，随意
    strategy:
      fail-fast: false
      matrix:
        include:
            # 只有此处是要改的，本文件（kernel-sm8650.yml）是可以复制的
            # 复制完可以取名kernel-sm8750.yml之类的，然后修改下面机型就行了，别的都不用管
        - FEIL: 'oneplus_12'
        - FEIL: 'oneplus_ace3_pro'
        - FEIL: 'oneplus_ace5'
        - FEIL: 'oneplus_13r'
        - FEIL: 'oneplus_pad_pro'
        
    uses: ./.github/workflows/Build_Sukisu.yml
    secrets: inherit
    with:
      CPU: ${{ inputs.CPU }}
      FEIL: ${{ matrix.FEIL }}
      CPUD: ${{ inputs.CPUD }}
      ANDROID_VERSION: ${{ inputs.ANDROID_VERSION }}
      KERNEL_VERSION: ${{ inputs.KERNEL_VERSION }}
      KPM: ${{ inputs.KPM }}
      lz4kd: ${{ inputs.lz4kd }}
      bbr: ${{ inputs.bbr }}
      proxy: ${{ inputs.proxy }}
